import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('lyra', {
  control: (cmd: string, arg?: number) => ipcRenderer.invoke('lyra:control', cmd, arg) as Promise<boolean>,
  playTrack: (t: unknown, order: unknown) => ipcRenderer.invoke('lyra:play-track', t, order) as Promise<{ ok: boolean; reason?: string; audioSource?: string }>,
  search: (q: string, source: string) => ipcRenderer.invoke('lyra:search', q, source) as Promise<unknown[]>,
  spotifySearch: (q: string) => ipcRenderer.invoke('lyra:spotify-search', q) as Promise<unknown[]>,
  localPick: () => ipcRenderer.invoke('lyra:local-pick') as Promise<{ folders: string[]; tracks: unknown[] } | null>,
  localScan: (folders: string[]) => ipcRenderer.invoke('lyra:local-scan', folders) as Promise<unknown[]>,
  downloadStart: (url: string, format: string, dest?: string) => ipcRenderer.invoke('lyra:download-start', url, format, dest) as Promise<string>,
  downloadCancel: (id: string) => ipcRenderer.invoke('lyra:download-cancel', id) as Promise<boolean>,
  onDownloadProgress: (cb: (m: { id: string; status: string; progress?: number; file?: string }) => void) => ipcRenderer.on('lyra:download-progress', (_e, m) => cb(m)),
  pickFolder: () => ipcRenderer.invoke('lyra:pick-folder') as Promise<string | null>,
  cacheDir: () => ipcRenderer.invoke('lyra:cache-dir') as Promise<string>,
  findLocal: (folder: string, q: unknown) => ipcRenderer.invoke('lyra:find-local', folder, q) as Promise<(string | null)[]>,
  notify: (t: string, b: string) => ipcRenderer.invoke('lyra:notify', t, b) as Promise<boolean>,
  mpris: (k: string, p?: unknown) => ipcRenderer.invoke('lyra:mpris', k, p) as Promise<boolean>,
  ytdlpVersion: () => ipcRenderer.invoke('lyra:ytdlp-version') as Promise<string>,
  ytdlpUpdate: () => ipcRenderer.invoke('lyra:ytdlp-update') as Promise<string>,
  userAgent: () => ipcRenderer.invoke('lyra:user-agent') as Promise<string>,
  lyrics: (t: string, a: string) => ipcRenderer.invoke('lyra:lyrics-lrclib', t, a) as Promise<unknown>,
  login: (w: string) => ipcRenderer.invoke('lyra:login', w) as Promise<boolean>,
  spotifyOauth: () => ipcRenderer.invoke('lyra:spotify-oauth') as Promise<boolean>,
  spotifyLibrary: (k: string) => ipcRenderer.invoke('lyra:spotify-library', k) as Promise<unknown[]>,
  scLibrary: (k: string) => ipcRenderer.invoke('lyra:sc-library', k) as Promise<unknown[]>,
  scCharts: () => ipcRenderer.invoke('lyra:sc-charts') as Promise<unknown[]>,
  searchPlaylists: (q: string, s: string) => ipcRenderer.invoke('lyra:search-playlists', q, s) as Promise<unknown[]>,
  playlistTracks: (s: string, r: unknown) => ipcRenderer.invoke('lyra:playlist-tracks', s, r) as Promise<unknown[]>,
  playlistCovers: (s: string, id: unknown) => ipcRenderer.invoke('lyra:playlist-covers', s, id) as Promise<string[]>,
  win: (cmd: string) => ipcRenderer.invoke('lyra:win', cmd) as Promise<unknown>,
  authStatus: (w: string) => ipcRenderer.invoke('lyra:auth-status', w) as Promise<{ connected: boolean; name?: string }>,
  sidecarLyrics: (p: string) => ipcRenderer.invoke('lyra:sidecar-lyrics', p) as Promise<string | null>,
  onLoginDone: (cb: (w: string) => void) => ipcRenderer.on('lyra:login-done', (_e, w) => cb(w)),
  authClear: (keys: string[]) => ipcRenderer.invoke('lyra:auth-clear', keys) as Promise<boolean>,
  defaultMusicDir: () => ipcRenderer.invoke('lyra:default-music-dir') as Promise<string>,
  onEnded: (cb: () => void) => ipcRenderer.on('lyra:ended', () => cb()),
  onMprisCmd: (cb: (m: { action: string; arg?: number }) => void) => ipcRenderer.on('lyra:mpris-cmd', (_e, m) => cb(m)),
  onMpv: (cb: (m: { name: string; value: unknown }) => void) => ipcRenderer.on('lyra:mpv', (_e, m) => cb(m)),
});
